tap "clementtsang/bottom"
tap "d12frosted/emacs-plus"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "mistertea/et"
tap "nodenv/nodenv"
# Bourne-Again SHell, a UNIX command interpreter
brew "bash"
# Cryptography and SSL/TLS Toolkit
brew "openssl@1.1"
# Command-line interface for SQLite
brew "sqlite"
# Interpreted, interactive, object-oriented programming language
brew "python@3.8"
# Formatting tools for C, C++, Obj-C, Java, JavaScript, TypeScript
brew "clang-format"
# Cross-platform make
brew "cmake"
# GNU File, Shell, and Text utilities
brew "coreutils"
# Configurable talking characters in ASCII art
brew "cowsay"
# Get a file from an HTTP, HTTPS or FTP server
brew "curl"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Command-line fuzzy finder written in Go
brew "fzf"
# GNU compiler collection
brew "gcc"
# Distributed revision control system
brew "git"
# Command-driven, interactive function plotting
brew "gnuplot"
# Graph visualization software from AT&T and Bell Labs
brew "graphviz"
# Add GitHub support to git on the command-line
brew "hub"
# Tools and libraries to manipulate images in many formats
brew "imagemagick"
# Manage your Java environment
brew "jenv"
# C99 library which implements a VT220 or xterm terminal emulator
brew "libvterm"
# Next-gen compiler infrastructure
brew "llvm"
# Mac App Store command-line interface
brew "mas"
# Development kit for the Java programming language
brew "openjdk"
# Java-based project management
brew "maven"
# Minimalist GNU for Windows and GCC cross-compilers
brew "mingw-w64"
# Install NodeJS versions
brew "node-build"
# Manage multiple NodeJS versions
brew "nodenv"
# 7-Zip (high compression file archiver) implementation
brew "p7zip"
# Swiss-army knife of markup format conversion
brew "pandoc"
# Object-relational database system
brew "postgresql"
# Python version management
brew "pyenv"
# Migrate pip packages from one Python version to another
brew "pyenv-pip-migrate"
# Pyenv plugin to manage virtualenv
brew "pyenv-virtualenv"
# Integrate pyenv and system commands
brew "pyenv-which-ext"
# Install various Ruby versions and implementations
brew "ruby-build"
# Ruby version manager
brew "rbenv"
# Auto-installs gems for Ruby installs
brew "rbenv-default-gems"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# User interface to the TELNET protocol
brew "telnet"
# Programatically correct mistyped console commands
brew "thefuck"
# Simplified and community-driven man pages
brew "tldr"
# Terminal multiplexer
brew "tmux"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Internet file retriever
brew "wget"
# JavaScript package manager
brew "yarn"
# Tracks most-used directories to make cd smarter
brew "z"
# UNIX shell (command interpreter)
brew "zsh"
# A cross-platform graphical process/system monitor with a customizable interface and a multitude of features.
brew "clementtsang/bottom/bottom"
brew "d12frosted/emacs-plus/emacs-plus@27"
# Everything you need to get started with Heroku
brew "heroku/brew/heroku"
# Remote terminal with IP roaming
brew "mistertea/et/et"
# Fix IntelliJ/WebStorm's npm integration under nodenv
brew "nodenv/nodenv/jetbrains-npm"
# Auto-installs packages for Node installs
brew "nodenv/nodenv/nodenv-default-packages"
# Migrate npm packages from one Node version to another
brew "nodenv/nodenv/nodenv-npm-migrate"
# Automatically runs `nodenv rehash`
brew "nodenv/nodenv/nodenv-package-rehash"
# Update nodenv plugins not installed with Homebrew
brew "nodenv/nodenv/nodenv-update"
cask "adobe-acrobat-reader"
cask "alfred"
cask "android-platform-tools"
cask "bartender"
cask "dash"
cask "dotnet-sdk"
cask "dropbox"
cask "firefox"
cask "flash-player"
cask "font-anonymice-powerline"
cask "font-consolas-for-powerline"
cask "font-dejavu-sans-mono-for-powerline"
cask "font-droid-sans-mono-for-powerline"
cask "font-fira-mono-for-powerline"
cask "font-inconsolata-dz-for-powerline"
cask "font-inconsolata-for-powerline"
cask "font-inconsolata-g-for-powerline"
cask "font-liberation-mono-for-powerline"
cask "font-menlo-for-powerline"
cask "font-meslo-for-powerline"
cask "font-monofur-for-powerline"
cask "font-noto-mono-for-powerline"
cask "font-roboto-mono-for-powerline"
cask "font-source-code-pro-for-powerline"
cask "font-ubuntu-mono-derivative-powerline"
cask "free-download-manager"
cask "google-backup-and-sync"
cask "google-chrome"
cask "iina"
cask "iterm2"
cask "itsycal"
cask "java"
cask "jetbrains-toolbox"
cask "karabiner-elements"
cask "keka"
cask "krita"
cask "mactex"
cask "malwarebytes"
cask "mathpix-snipping-tool"
cask "miniconda"
cask "mono-mdk"
cask "ngrok"
cask "pomodone"
cask "powershell"
cask "rectangle"
cask "scroll-reverser"
cask "sensiblesidebuttons"
cask "sidequest"
cask "skype"
cask "spotify"
cask "sublime-text"
cask "virtualbox"
cask "virtualbox-extension-pack"
cask "visual-studio-code"
mas "Amphetamine", id: 937984704
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Irvue", id: 1039633667
mas "Keynote", id: 409183694
mas "LastPass", id: 926036361
mas "Messenger", id: 1480068668
mas "Microsoft To Do", id: 1274495053
mas "Numbers", id: 409203825
mas "OneDrive", id: 823766827
mas "Pages", id: 409201541
mas "PhotoScape X", id: 929507092
mas "Spark", id: 1176895641
mas "Xcode", id: 497799835
